<?php

// Generated by Jws_Acf_Compat::export_schema_file() — snapshot of the ACF field groups.

return array (
  'fields' => 
  array (
    'field_adsvmap_preroll' => 
    array (
      'key' => 'field_adsvmap_preroll',
      'name' => 'preroll',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_adsvmap_ads_tag',
          'name' => 'ads_tag',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => 0,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'advertising',
          ),
        ),
      ),
    ),
    'field_adsvmap_midroll' => 
    array (
      'key' => 'field_adsvmap_midroll',
      'name' => 'midroll',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_adsvmap_ads_tag_mid',
          'name' => 'ads_tag_mid',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => 0,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'advertising',
          ),
        ),
        1 => 
        array (
          'key' => 'field_adsvmap_time_offset',
          'name' => 'time_offset',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_adsvmap_postroll' => 
    array (
      'key' => 'field_adsvmap_postroll',
      'name' => 'postroll',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_adsvmap_ads_tag_end',
          'name' => 'ads_tag_end',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => 0,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'advertising',
          ),
        ),
      ),
    ),
    'field_ads_ads_server' => 
    array (
      'key' => 'field_ads_ads_server',
      'name' => 'ads_server',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_ads_ads_target_url' => 
    array (
      'key' => 'field_ads_ads_target_url',
      'name' => 'ads_target_url',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_ads_ads_type' => 
    array (
      'key' => 'field_ads_ads_type',
      'name' => 'ads_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_ads_ads_banner' => 
    array (
      'key' => 'field_ads_ads_banner',
      'name' => 'ads_banner',
      'type' => 'group',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_ads_ads_banner_image',
          'name' => 'ads_banner_image',
          'type' => 'image',
          'return_format' => 'id',
        ),
        1 => 
        array (
          'key' => 'field_ads_ads_banner_position',
          'name' => 'ads_banner_position',
          'type' => 'select',
          'return_format' => 'value',
          'multiple' => 0,
          'default_value' => '',
        ),
      ),
    ),
    'field_ads_ads_duration' => 
    array (
      'key' => 'field_ads_ads_duration',
      'name' => 'ads_duration',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_ads_ads_video_source' => 
    array (
      'key' => 'field_ads_ads_video_source',
      'name' => 'ads_video_source',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'file',
    ),
    'field_ads_ads_video' => 
    array (
      'key' => 'field_ads_ads_video',
      'name' => 'ads_video',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_ads_ads_video_url' => 
    array (
      'key' => 'field_ads_ads_video_url',
      'name' => 'ads_video_url',
      'type' => 'url',
      'default_value' => '',
    ),
    'field_ads_ads_skippable' => 
    array (
      'key' => 'field_ads_ads_skippable',
      'name' => 'ads_skippable',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_ads_ads_vast_url' => 
    array (
      'key' => 'field_ads_ads_vast_url',
      'name' => 'ads_vast_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_age_ages_badge' => 
    array (
      'key' => 'field_age_ages_badge',
      'name' => 'ages_badge',
      'type' => 'text',
      'default_value' => '',
    ),
    'blog_audio_url' => 
    array (
      'key' => 'blog_audio_url',
      'name' => 'blog_audio_url',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_drama_status' => 
    array (
      'key' => 'field_drama_status',
      'name' => 'drama_status',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'ongoing',
    ),
    'field_drama_total_ep' => 
    array (
      'key' => 'field_drama_total_ep',
      'name' => 'drama_total_ep',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_drama_trailer' => 
    array (
      'key' => 'field_drama_trailer',
      'name' => 'drama_trailer',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_drama_genres' => 
    array (
      'key' => 'field_drama_genres',
      'name' => 'drama_genres',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'genres',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_drama_countries' => 
    array (
      'key' => 'field_drama_countries',
      'name' => 'drama_countries',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'countries',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_drama_ages' => 
    array (
      'key' => 'field_drama_ages',
      'name' => 'drama_ages',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 0,
      'field_type' => 'select',
      'taxonomy' => 'ages',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_drama_tags' => 
    array (
      'key' => 'field_drama_tags',
      'name' => 'drama_tags',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'drama_tag',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_drama_free_ep' => 
    array (
      'key' => 'field_drama_free_ep',
      'name' => 'drama_free_ep',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_drama_coin_per_ep' => 
    array (
      'key' => 'field_drama_coin_per_ep',
      'name' => 'drama_coin_per_ep',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_drama_side_featured_image_two' => 
    array (
      'key' => 'field_drama_side_featured_image_two',
      'name' => 'featured_image_two',
      'type' => 'image',
      'return_format' => 'id',
    ),
    'field_drama_ep_drama_id' => 
    array (
      'key' => 'field_drama_ep_drama_id',
      'name' => 'drama_id',
      'type' => 'post_object',
      'return_format' => 'id',
      'multiple' => 0,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'drama',
      ),
    ),
    'field_drama_ep_number' => 
    array (
      'key' => 'field_drama_ep_number',
      'name' => 'drama_ep_number',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_drama_ep_free' => 
    array (
      'key' => 'field_drama_ep_free',
      'name' => 'drama_ep_free',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_drama_ep_duration' => 
    array (
      'key' => 'field_drama_ep_duration',
      'name' => 'videos_time',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_drama_ep_videos_type' => 
    array (
      'key' => 'field_drama_ep_videos_type',
      'name' => 'videos_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'url',
    ),
    'field_drama_ep_videos_file' => 
    array (
      'key' => 'field_drama_ep_videos_file',
      'name' => 'videos_file',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_drama_ep_videos_url' => 
    array (
      'key' => 'field_drama_ep_videos_url',
      'name' => 'videos_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_drama_ep_quality_lists' => 
    array (
      'key' => 'field_drama_ep_quality_lists',
      'name' => 'quality_lists',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_drama_ep_quality_label',
          'name' => 'label',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_drama_ep_quality_url',
          'name' => 'quality_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_drama_ep_sub_titles' => 
    array (
      'key' => 'field_drama_ep_sub_titles',
      'name' => 'sub_titles',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_drama_ep_sub_language',
          'name' => 'language',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_drama_ep_sub_vtt_file',
          'name' => 'vtt_file',
          'type' => 'file',
          'return_format' => 'array',
        ),
        2 => 
        array (
          'key' => 'field_drama_ep_sub_vtt_url',
          'name' => 'vtt_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_ep_videos_type' => 
    array (
      'key' => 'field_ep_videos_type',
      'name' => 'videos_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_ep_videos_file' => 
    array (
      'key' => 'field_ep_videos_file',
      'name' => 'videos_file',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_ep_videos_url' => 
    array (
      'key' => 'field_ep_videos_url',
      'name' => 'videos_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_ep_quality_lists' => 
    array (
      'key' => 'field_ep_quality_lists',
      'name' => 'quality_lists',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_ep_label',
          'name' => 'label',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_ep_quality_url',
          'name' => 'quality_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_ep_episodes_number' => 
    array (
      'key' => 'field_ep_episodes_number',
      'name' => 'episodes_number',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_ep_videos_time' => 
    array (
      'key' => 'field_ep_videos_time',
      'name' => 'videos_time',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_ep_videos_tmdb' => 
    array (
      'key' => 'field_ep_videos_tmdb',
      'name' => 'videos_tmdb',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_ep_sub_titles' => 
    array (
      'key' => 'field_ep_sub_titles',
      'name' => 'sub_titles',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_ep_language',
          'name' => 'language',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_ep_vtt_file',
          'name' => 'vtt_file',
          'type' => 'file',
          'return_format' => 'array',
        ),
        2 => 
        array (
          'key' => 'field_ep_vtt_url',
          'name' => 'vtt_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_ep_sources' => 
    array (
      'key' => 'field_ep_sources',
      'name' => 'sources',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_ep_main',
          'name' => 'main',
          'type' => 'true_false',
          'default_value' => 0,
        ),
        1 => 
        array (
          'key' => 'field_ep_url',
          'name' => 'url',
          'type' => 'textarea',
          'default_value' => '',
        ),
        2 => 
        array (
          'key' => 'field_ep_quality',
          'name' => 'quality',
          'type' => 'text',
          'default_value' => '',
        ),
        3 => 
        array (
          'key' => 'field_ep_language',
          'name' => 'language',
          'type' => 'text',
          'default_value' => '',
        ),
        4 => 
        array (
          'key' => 'field_ep_player',
          'name' => 'player',
          'type' => 'text',
          'default_value' => '',
        ),
        5 => 
        array (
          'key' => 'field_ep_date',
          'name' => 'date',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_ep_download' => 
    array (
      'key' => 'field_ep_download',
      'name' => 'download',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_ep_download_list' => 
    array (
      'key' => 'field_ep_download_list',
      'name' => 'download_list',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_ep_download_name',
          'name' => 'download_name',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_ep_download_url',
          'name' => 'download_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_ep_videos_preview' => 
    array (
      'key' => 'field_ep_videos_preview',
      'name' => 'videos_preview',
      'type' => 'videos_preview',
    ),
    'image_gallery_list' => 
    array (
      'key' => 'image_gallery_list',
      'name' => 'image_gallery_list',
      'type' => 'gallery',
      'return_format' => 'array',
    ),
    'field_genres_color_background' => 
    array (
      'key' => 'field_genres_color_background',
      'name' => 'color_background',
      'type' => 'color_picker',
      'return_format' => 'string',
      'default_value' => '',
    ),
    'field_genres_color_background2' => 
    array (
      'key' => 'field_genres_color_background2',
      'name' => 'color_background2',
      'type' => 'color_picker',
      'return_format' => 'string',
      'default_value' => '',
    ),
    'field_genres_genres_image' => 
    array (
      'key' => 'field_genres_genres_image',
      'name' => 'genres_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'blog_name_link' => 
    array (
      'key' => 'blog_name_link',
      'name' => 'blog_name_link',
      'type' => 'text',
      'default_value' => '',
    ),
    'blog_url_link' => 
    array (
      'key' => 'blog_url_link',
      'name' => 'blog_url_link',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_type' => 
    array (
      'key' => 'field_mov_videos_type',
      'name' => 'videos_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_mov_videos_file' => 
    array (
      'key' => 'field_mov_videos_file',
      'name' => 'videos_file',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_mov_videos_url' => 
    array (
      'key' => 'field_mov_videos_url',
      'name' => 'videos_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_mov_quality_lists' => 
    array (
      'key' => 'field_mov_quality_lists',
      'name' => 'quality_lists',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_mov_label',
          'name' => 'label',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_mov_quality_url',
          'name' => 'quality_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_mov_is_affiliate' => 
    array (
      'key' => 'field_mov_is_affiliate',
      'name' => 'is_affiliate',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_mov_sub_titles' => 
    array (
      'key' => 'field_mov_sub_titles',
      'name' => 'sub_titles',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_mov_language',
          'name' => 'language',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_mov_vtt_file',
          'name' => 'vtt_file',
          'type' => 'file',
          'return_format' => 'array',
        ),
        2 => 
        array (
          'key' => 'field_mov_vtt_url',
          'name' => 'vtt_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_mov_videos_trailer_type' => 
    array (
      'key' => 'field_mov_videos_trailer_type',
      'name' => 'videos_trailer_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_mov_videos_trailer_file' => 
    array (
      'key' => 'field_mov_videos_trailer_file',
      'name' => 'videos_trailer_file',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_mov_videos_trailer_url' => 
    array (
      'key' => 'field_mov_videos_trailer_url',
      'name' => 'videos_trailer_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_mov_videos_tmdb' => 
    array (
      'key' => 'field_mov_videos_tmdb',
      'name' => 'videos_tmdb',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_vote' => 
    array (
      'key' => 'field_mov_videos_vote',
      'name' => 'videos_vote',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_imdb_id' => 
    array (
      'key' => 'field_mov_videos_imdb_id',
      'name' => 'videos_imdb_id',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_imdb' => 
    array (
      'key' => 'field_mov_videos_imdb',
      'name' => 'videos_imdb',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_years' => 
    array (
      'key' => 'field_mov_videos_years',
      'name' => 'videos_years',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_time' => 
    array (
      'key' => 'field_mov_videos_time',
      'name' => 'videos_time',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_badge' => 
    array (
      'key' => 'field_mov_videos_badge',
      'name' => 'videos_badge',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_videos_age' => 
    array (
      'key' => 'field_mov_videos_age',
      'name' => 'videos_age',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_mov_videos_language' => 
    array (
      'key' => 'field_mov_videos_language',
      'name' => 'videos_language',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_buy_enable' => 
    array (
      'key' => 'field_mov_buy_enable',
      'name' => 'buy_enable',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_mov_buy_price' => 
    array (
      'key' => 'field_mov_buy_price',
      'name' => 'buy_price',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_mov_rent_enable' => 
    array (
      'key' => 'field_mov_rent_enable',
      'name' => 'rent_enable',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_mov_rent_price' => 
    array (
      'key' => 'field_mov_rent_price',
      'name' => 'rent_price',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_mov_rent_day' => 
    array (
      'key' => 'field_mov_rent_day',
      'name' => 'rent_day',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_mov_cast' => 
    array (
      'key' => 'field_mov_cast',
      'name' => 'cast',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_mov_person',
          'name' => 'person',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => false,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'person',
          ),
        ),
        1 => 
        array (
          'key' => 'field_mov_as',
          'name' => 'as',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_mov_crew' => 
    array (
      'key' => 'field_mov_crew',
      'name' => 'crew',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_mov_crew_person',
          'name' => 'person',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => false,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'person',
          ),
        ),
        1 => 
        array (
          'key' => 'field_mov_job',
          'name' => 'job',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_mov_sources' => 
    array (
      'key' => 'field_mov_sources',
      'name' => 'sources',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_mov_main',
          'name' => 'main',
          'type' => 'true_false',
          'default_value' => 0,
        ),
        1 => 
        array (
          'key' => 'field_mov_url',
          'name' => 'url',
          'type' => 'textarea',
          'default_value' => '',
        ),
        2 => 
        array (
          'key' => 'field_mov_quality',
          'name' => 'quality',
          'type' => 'text',
          'default_value' => '',
        ),
        3 => 
        array (
          'key' => 'field_mov_language',
          'name' => 'language',
          'type' => 'text',
          'default_value' => '',
        ),
        4 => 
        array (
          'key' => 'field_mov_player',
          'name' => 'player',
          'type' => 'text',
          'default_value' => '',
        ),
        5 => 
        array (
          'key' => 'field_mov_date',
          'name' => 'date',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_mov_download' => 
    array (
      'key' => 'field_mov_download',
      'name' => 'download',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_mov_download_list' => 
    array (
      'key' => 'field_mov_download_list',
      'name' => 'download_list',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_mov_download_name',
          'name' => 'download_name',
          'type' => 'text',
          'default_value' => '',
        ),
        1 => 
        array (
          'key' => 'field_mov_download_url',
          'name' => 'download_url',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_mov_videos_ads_special' => 
    array (
      'key' => 'field_mov_videos_ads_special',
      'name' => 'videos_ads_special',
      'type' => 'post_object',
      'return_format' => 'id',
      'multiple' => false,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'adsvmap',
      ),
    ),
    'field_mov_recommended' => 
    array (
      'key' => 'field_mov_recommended',
      'name' => 'recommended',
      'type' => 'relationship',
      'return_format' => 'id',
      'multiple' => true,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'movies',
        1 => 'tv_shows',
      ),
    ),
    'field_mov_featured_clips' => 
    array (
      'key' => 'field_mov_featured_clips',
      'name' => 'featured_clips',
      'type' => 'relationship',
      'return_format' => 'id',
      'multiple' => true,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'videos',
      ),
    ),
    'field_mov_videos_gallery' => 
    array (
      'key' => 'field_mov_videos_gallery',
      'name' => 'videos_gallery',
      'type' => 'gallery',
      'return_format' => 'id',
    ),
    'field_mov_movie_topics' => 
    array (
      'key' => 'field_mov_movie_topics',
      'name' => 'movie_topics',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'topics',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_movie_genres' => 
    array (
      'key' => 'field_mov_movie_genres',
      'name' => 'movie_genres',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'genres',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_movie_countries' => 
    array (
      'key' => 'field_mov_movie_countries',
      'name' => 'movie_countries',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'countries',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_movie_ages' => 
    array (
      'key' => 'field_mov_movie_ages',
      'name' => 'movie_ages',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 0,
      'field_type' => 'select',
      'taxonomy' => 'ages',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_movie_category' => 
    array (
      'key' => 'field_mov_movie_category',
      'name' => 'movie_category',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'movies_cat',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_movie_tags' => 
    array (
      'key' => 'field_mov_movie_tags',
      'name' => 'movie_tags',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'movies_tag',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_movie_playlist' => 
    array (
      'key' => 'field_mov_movie_playlist',
      'name' => 'movie_playlist',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'movies_playlist',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_mov_videos_preview' => 
    array (
      'key' => 'field_mov_videos_preview',
      'name' => 'videos_preview',
      'type' => 'videos_preview',
    ),
    'field_mov_featured_image_two' => 
    array (
      'key' => 'field_mov_featured_image_two',
      'name' => 'featured_image_two',
      'type' => 'image',
      'return_format' => 'id',
    ),
    'field_mov_title_images' => 
    array (
      'key' => 'field_mov_title_images',
      'name' => 'title_images',
      'type' => 'image',
      'return_format' => 'id',
    ),
    'field_page_page_select_header' => 
    array (
      'key' => 'field_page_page_select_header',
      'name' => 'page_select_header',
      'type' => 'post_object',
      'return_format' => 'id',
      'multiple' => false,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'hf_template',
      ),
    ),
    'field_page_page_select_footer' => 
    array (
      'key' => 'field_page_page_select_footer',
      'name' => 'page_select_footer',
      'type' => 'post_object',
      'return_format' => 'id',
      'multiple' => false,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'hf_template',
      ),
    ),
    'field_page_turn_off_header' => 
    array (
      'key' => 'field_page_turn_off_header',
      'name' => 'turn_off_header',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_page_turn_on_header_sidebar' => 
    array (
      'key' => 'field_page_turn_on_header_sidebar',
      'name' => 'turn_on_header_sidebar',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_page_turn_off_footer' => 
    array (
      'key' => 'field_page_turn_off_footer',
      'name' => 'turn_off_footer',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_page_title_bar_checkbox' => 
    array (
      'key' => 'field_page_title_bar_checkbox',
      'name' => 'title_bar_checkbox',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_page_tool_bar_checkbox' => 
    array (
      'key' => 'field_page_tool_bar_checkbox',
      'name' => 'tool_bar_checkbox',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_page_page_header_absolute' => 
    array (
      'key' => 'field_page_page_header_absolute',
      'name' => 'page_header_absolute',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_person_know' => 
    array (
      'key' => 'field_person_know',
      'name' => 'know',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_person_gender' => 
    array (
      'key' => 'field_person_gender',
      'name' => 'gender',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_person_birthday' => 
    array (
      'key' => 'field_person_birthday',
      'name' => 'birthday',
      'type' => 'date_picker',
      'return_format' => 'd/m/Y',
    ),
    'field_person_address' => 
    array (
      'key' => 'field_person_address',
      'name' => 'address',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_person_know_as' => 
    array (
      'key' => 'field_person_know_as',
      'name' => 'know_as',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_person_videos_tmdb' => 
    array (
      'key' => 'field_person_videos_tmdb',
      'name' => 'videos_tmdb',
      'type' => 'text',
      'default_value' => '',
    ),
    'blog_name_quote' => 
    array (
      'key' => 'blog_name_quote',
      'name' => 'blog_name_quote',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_mov_playlist_image' => 
    array (
      'key' => 'field_mov_playlist_image',
      'name' => 'playlist_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'field_mov_status' => 
    array (
      'key' => 'field_mov_status',
      'name' => 'status',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'public',
    ),
    'field_mov_user' => 
    array (
      'key' => 'field_mov_user',
      'name' => 'user',
      'type' => 'user',
      'return_format' => 'array',
      'multiple' => 0,
    ),
    'field_ep_playlist_image' => 
    array (
      'key' => 'field_ep_playlist_image',
      'name' => 'playlist_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'field_ep_status' => 
    array (
      'key' => 'field_ep_status',
      'name' => 'status',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'public',
    ),
    'field_ep_user' => 
    array (
      'key' => 'field_ep_user',
      'name' => 'user',
      'type' => 'user',
      'return_format' => 'array',
      'multiple' => 0,
    ),
    'field_tvs_color_background' => 
    array (
      'key' => 'field_tvs_color_background',
      'name' => 'color_background',
      'type' => 'color_picker',
      'return_format' => 'string',
      'default_value' => '',
    ),
    'field_tvs_color_background2' => 
    array (
      'key' => 'field_tvs_color_background2',
      'name' => 'color_background2',
      'type' => 'color_picker',
      'return_format' => 'string',
      'default_value' => '',
    ),
    'field_tvs_tv_shows_cat_image' => 
    array (
      'key' => 'field_tvs_tv_shows_cat_image',
      'name' => 'tv_shows_cat_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'field_tvs_playlist_image' => 
    array (
      'key' => 'field_tvs_playlist_image',
      'name' => 'playlist_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'field_tvs_status' => 
    array (
      'key' => 'field_tvs_status',
      'name' => 'status',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'public',
    ),
    'field_tvs_user' => 
    array (
      'key' => 'field_tvs_user',
      'name' => 'user',
      'type' => 'user',
      'return_format' => 'array',
      'multiple' => 0,
    ),
    'field_vd_playlist_image' => 
    array (
      'key' => 'field_vd_playlist_image',
      'name' => 'playlist_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'field_vd_status' => 
    array (
      'key' => 'field_vd_status',
      'name' => 'status',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => 'public',
    ),
    'field_vd_user' => 
    array (
      'key' => 'field_vd_user',
      'name' => 'user',
      'type' => 'user',
      'return_format' => 'array',
      'multiple' => 0,
    ),
    'field_topic_featured_content' => 
    array (
      'key' => 'field_topic_featured_content',
      'name' => 'topic_featured_content',
      'type' => 'relationship',
      'return_format' => 'id',
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'movies',
        1 => 'tv_shows',
      ),
    ),
    'field_topic_color_background' => 
    array (
      'key' => 'field_topic_color_background',
      'name' => 'color_background',
      'type' => 'color_picker',
      'return_format' => 'string',
      'default_value' => '',
    ),
    'field_topic_color_background2' => 
    array (
      'key' => 'field_topic_color_background2',
      'name' => 'color_background2',
      'type' => 'color_picker',
      'return_format' => 'string',
      'default_value' => '',
    ),
    'field_topic_topics_image' => 
    array (
      'key' => 'field_topic_topics_image',
      'name' => 'topics_image',
      'type' => 'image',
      'return_format' => 'array',
    ),
    'field_tvs_videos_years' => 
    array (
      'key' => 'field_tvs_videos_years',
      'name' => 'videos_years',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_tvs_videos_tmdb' => 
    array (
      'key' => 'field_tvs_videos_tmdb',
      'name' => 'videos_tmdb',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_tvs_videos_vote' => 
    array (
      'key' => 'field_tvs_videos_vote',
      'name' => 'videos_vote',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_tvs_videos_imdb_id' => 
    array (
      'key' => 'field_tvs_videos_imdb_id',
      'name' => 'videos_imdb_id',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_tvs_videos_imdb' => 
    array (
      'key' => 'field_tvs_videos_imdb',
      'name' => 'videos_imdb',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_tvs_videos_badge' => 
    array (
      'key' => 'field_tvs_videos_badge',
      'name' => 'videos_badge',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_tvs_featured_clips' => 
    array (
      'key' => 'field_tvs_featured_clips',
      'name' => 'featured_clips',
      'type' => 'relationship',
      'return_format' => 'id',
      'multiple' => true,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'videos',
      ),
    ),
    'field_tvs_videos_trailer_type' => 
    array (
      'key' => 'field_tvs_videos_trailer_type',
      'name' => 'videos_trailer_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_tvs_videos_trailer_file' => 
    array (
      'key' => 'field_tvs_videos_trailer_file',
      'name' => 'videos_trailer_file',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_tvs_videos_trailer_url' => 
    array (
      'key' => 'field_tvs_videos_trailer_url',
      'name' => 'videos_trailer_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_tvs_tv_shows_seasons' => 
    array (
      'key' => 'field_tvs_tv_shows_seasons',
      'name' => 'tv_shows_seasons',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_tvs_season_thumbnail',
          'name' => 'season_thumbnail',
          'type' => 'image',
          'return_format' => 'id',
        ),
        1 => 
        array (
          'key' => 'field_tvs_season_name',
          'name' => 'season_name',
          'type' => 'text',
          'default_value' => '',
        ),
        2 => 
        array (
          'key' => 'field_tvs_episodes',
          'name' => 'episodes',
          'type' => 'relationship',
          'return_format' => 'id',
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'episodes',
          ),
        ),
      ),
    ),
    'field_tvs_buy_enable' => 
    array (
      'key' => 'field_tvs_buy_enable',
      'name' => 'buy_enable',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_tvs_buy_price' => 
    array (
      'key' => 'field_tvs_buy_price',
      'name' => 'buy_price',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_tvs_rent_enable' => 
    array (
      'key' => 'field_tvs_rent_enable',
      'name' => 'rent_enable',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    'field_tvs_rent_price' => 
    array (
      'key' => 'field_tvs_rent_price',
      'name' => 'rent_price',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_tvs_rent_day' => 
    array (
      'key' => 'field_tvs_rent_day',
      'name' => 'rent_day',
      'type' => 'number',
      'default_value' => '',
    ),
    'field_tvs_cast' => 
    array (
      'key' => 'field_tvs_cast',
      'name' => 'cast',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_tvs_person',
          'name' => 'person',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => false,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'person',
          ),
        ),
        1 => 
        array (
          'key' => 'field_tvs_as',
          'name' => 'as',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_tvs_crew' => 
    array (
      'key' => 'field_tvs_crew',
      'name' => 'crew',
      'type' => 'repeater',
      'sub_fields' => 
      array (
        0 => 
        array (
          'key' => 'field_tvs_crew_person',
          'name' => 'person',
          'type' => 'post_object',
          'return_format' => 'id',
          'multiple' => false,
          'taxonomy' => 
          array (
          ),
          'post_type' => 
          array (
            0 => 'person',
          ),
        ),
        1 => 
        array (
          'key' => 'field_tvs_job',
          'name' => 'job',
          'type' => 'text',
          'default_value' => '',
        ),
      ),
    ),
    'field_tvs_videos_ads_special' => 
    array (
      'key' => 'field_tvs_videos_ads_special',
      'name' => 'videos_ads_special',
      'type' => 'post_object',
      'return_format' => 'id',
      'multiple' => false,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'adsvmap',
      ),
    ),
    'field_tvs_topics' => 
    array (
      'key' => 'field_tvs_topics',
      'name' => 'tvshow_topics',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'topics',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_tvs_genres' => 
    array (
      'key' => 'field_tvs_genres',
      'name' => 'tvshow_genres',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'genres',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_tvs_countries' => 
    array (
      'key' => 'field_tvs_countries',
      'name' => 'tvshow_countries',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'countries',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_tvs_ages' => 
    array (
      'key' => 'field_tvs_ages',
      'name' => 'tvshow_ages',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 0,
      'field_type' => 'select',
      'taxonomy' => 'ages',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_tvs_category' => 
    array (
      'key' => 'field_tvs_category',
      'name' => 'tvshow_category',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'tv_shows_cat',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_tvs_tags' => 
    array (
      'key' => 'field_tvs_tags',
      'name' => 'tvshow_tags',
      'type' => 'taxonomy',
      'return_format' => 'id',
      'multiple' => 1,
      'field_type' => 'multi_select',
      'taxonomy' => 'tv_shows_tag',
      'load_terms' => true,
      'save_terms' => true,
    ),
    'field_tvs_featured_image_two' => 
    array (
      'key' => 'field_tvs_featured_image_two',
      'name' => 'featured_image_two',
      'type' => 'image',
      'return_format' => 'id',
    ),
    'field_tvs_title_images' => 
    array (
      'key' => 'field_tvs_title_images',
      'name' => 'title_images',
      'type' => 'image',
      'return_format' => 'id',
    ),
    'jws_date_of_birth' => 
    array (
      'key' => 'jws_date_of_birth',
      'name' => 'jws_date_of_birth',
      'type' => 'date_picker',
      'return_format' => 'd/m/Y',
    ),
    'jws_gender' => 
    array (
      'key' => 'jws_gender',
      'name' => 'jws_gender',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'jws_postcode' => 
    array (
      'key' => 'jws_postcode',
      'name' => 'jws_postcode',
      'type' => 'text',
      'default_value' => '',
    ),
    'user_phone' => 
    array (
      'key' => 'user_phone',
      'name' => 'user_phone',
      'type' => 'text',
      'default_value' => '',
    ),
    'blog_video' => 
    array (
      'key' => 'blog_video',
      'name' => 'blog_video',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_vd_videos_type' => 
    array (
      'key' => 'field_vd_videos_type',
      'name' => 'videos_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_vd_videos_file' => 
    array (
      'key' => 'field_vd_videos_file',
      'name' => 'videos_file',
      'type' => 'file',
      'return_format' => 'array',
    ),
    'field_vd_videos_url' => 
    array (
      'key' => 'field_vd_videos_url',
      'name' => 'videos_url',
      'type' => 'textarea',
      'default_value' => '',
    ),
    'field_vd_video_ratio' => 
    array (
      'key' => 'field_vd_video_ratio',
      'name' => 'video_ratio',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_vd_videos_time' => 
    array (
      'key' => 'field_vd_videos_time',
      'name' => 'videos_time',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_vd_live_data' => 
    array (
      'key' => 'field_vd_live_data',
      'name' => 'live_data',
      'type' => 'live_data',
    ),
    'field_vd_videos_ads_special' => 
    array (
      'key' => 'field_vd_videos_ads_special',
      'name' => 'videos_ads_special',
      'type' => 'post_object',
      'return_format' => 'id',
      'multiple' => false,
      'taxonomy' => 
      array (
      ),
      'post_type' => 
      array (
        0 => 'adsvmap',
      ),
    ),
    'field_vd_videos_preview' => 
    array (
      'key' => 'field_vd_videos_preview',
      'name' => 'videos_preview',
      'type' => 'videos_preview',
    ),
    'field_product_shop_single_layout' => 
    array (
      'key' => 'field_product_shop_single_layout',
      'name' => 'shop_single_layout',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_product_shop_single_thumbnail_position' => 
    array (
      'key' => 'field_product_shop_single_thumbnail_position',
      'name' => 'shop_single_thumbnail_position',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_product_shop_single_video_type' => 
    array (
      'key' => 'field_product_shop_single_video_type',
      'name' => 'shop_single_video_type',
      'type' => 'select',
      'return_format' => 'value',
      'multiple' => 0,
      'default_value' => '',
    ),
    'field_product_product_video' => 
    array (
      'key' => 'field_product_product_video',
      'name' => 'product_video',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_questions_product_name' => 
    array (
      'key' => 'field_questions_product_name',
      'name' => 'product_name',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_questions_product_email' => 
    array (
      'key' => 'field_questions_product_email',
      'name' => 'product_email',
      'type' => 'text',
      'default_value' => '',
    ),
    'field_questions_answer_content' => 
    array (
      'key' => 'field_questions_answer_content',
      'name' => 'answer_content',
      'type' => 'textarea',
      'default_value' => '',
    ),
  ),
  'names' => 
  array (
    'post_type:adsvmap' => 
    array (
      'preroll' => 'field_adsvmap_preroll',
      'midroll' => 'field_adsvmap_midroll',
      'postroll' => 'field_adsvmap_postroll',
    ),
    'post_type:advertising' => 
    array (
      'ads_server' => 'field_ads_ads_server',
      'ads_target_url' => 'field_ads_ads_target_url',
      'ads_type' => 'field_ads_ads_type',
      'ads_banner' => 'field_ads_ads_banner',
      'ads_duration' => 'field_ads_ads_duration',
      'ads_video_source' => 'field_ads_ads_video_source',
      'ads_video' => 'field_ads_ads_video',
      'ads_video_url' => 'field_ads_ads_video_url',
      'ads_skippable' => 'field_ads_ads_skippable',
      'ads_vast_url' => 'field_ads_ads_vast_url',
    ),
    'taxonomy:ages' => 
    array (
      'ages_badge' => 'field_age_ages_badge',
    ),
    'post_format:audio' => 
    array (
      'blog_audio_url' => 'blog_audio_url',
    ),
    'post_type:drama' => 
    array (
      'drama_status' => 'field_drama_status',
      'drama_total_ep' => 'field_drama_total_ep',
      'drama_trailer' => 'field_drama_trailer',
      'drama_genres' => 'field_drama_genres',
      'drama_countries' => 'field_drama_countries',
      'drama_ages' => 'field_drama_ages',
      'drama_tags' => 'field_drama_tags',
      'drama_free_ep' => 'field_drama_free_ep',
      'drama_coin_per_ep' => 'field_drama_coin_per_ep',
      'featured_image_two' => 'field_drama_side_featured_image_two',
    ),
    'post_type:drama_ep' => 
    array (
      'drama_id' => 'field_drama_ep_drama_id',
      'drama_ep_number' => 'field_drama_ep_number',
      'drama_ep_free' => 'field_drama_ep_free',
      'videos_time' => 'field_drama_ep_duration',
      'videos_type' => 'field_drama_ep_videos_type',
      'videos_file' => 'field_drama_ep_videos_file',
      'videos_url' => 'field_drama_ep_videos_url',
      'quality_lists' => 'field_drama_ep_quality_lists',
      'sub_titles' => 'field_drama_ep_sub_titles',
    ),
    'post_type:episodes' => 
    array (
      'videos_type' => 'field_ep_videos_type',
      'videos_file' => 'field_ep_videos_file',
      'videos_url' => 'field_ep_videos_url',
      'quality_lists' => 'field_ep_quality_lists',
      'episodes_number' => 'field_ep_episodes_number',
      'videos_time' => 'field_ep_videos_time',
      'videos_tmdb' => 'field_ep_videos_tmdb',
      'sub_titles' => 'field_ep_sub_titles',
      'sources' => 'field_ep_sources',
      'download' => 'field_ep_download',
      'download_list' => 'field_ep_download_list',
      'videos_preview' => 'field_ep_videos_preview',
    ),
    'post_format:gallery' => 
    array (
      'image_gallery_list' => 'image_gallery_list',
    ),
    'taxonomy:genres' => 
    array (
      'color_background' => 'field_genres_color_background',
      'color_background2' => 'field_genres_color_background2',
      'genres_image' => 'field_genres_genres_image',
    ),
    'post_format:link' => 
    array (
      'blog_name_link' => 'blog_name_link',
      'blog_url_link' => 'blog_url_link',
    ),
    'post_type:movies' => 
    array (
      'videos_type' => 'field_mov_videos_type',
      'videos_file' => 'field_mov_videos_file',
      'videos_url' => 'field_mov_videos_url',
      'quality_lists' => 'field_mov_quality_lists',
      'is_affiliate' => 'field_mov_is_affiliate',
      'sub_titles' => 'field_mov_sub_titles',
      'videos_trailer_type' => 'field_mov_videos_trailer_type',
      'videos_trailer_file' => 'field_mov_videos_trailer_file',
      'videos_trailer_url' => 'field_mov_videos_trailer_url',
      'videos_tmdb' => 'field_mov_videos_tmdb',
      'videos_vote' => 'field_mov_videos_vote',
      'videos_imdb_id' => 'field_mov_videos_imdb_id',
      'videos_imdb' => 'field_mov_videos_imdb',
      'videos_years' => 'field_mov_videos_years',
      'videos_time' => 'field_mov_videos_time',
      'videos_badge' => 'field_mov_videos_badge',
      'videos_age' => 'field_mov_videos_age',
      'videos_language' => 'field_mov_videos_language',
      'buy_enable' => 'field_mov_buy_enable',
      'buy_price' => 'field_mov_buy_price',
      'rent_enable' => 'field_mov_rent_enable',
      'rent_price' => 'field_mov_rent_price',
      'rent_day' => 'field_mov_rent_day',
      'cast' => 'field_mov_cast',
      'crew' => 'field_mov_crew',
      'sources' => 'field_mov_sources',
      'download' => 'field_mov_download',
      'download_list' => 'field_mov_download_list',
      'videos_ads_special' => 'field_mov_videos_ads_special',
      'recommended' => 'field_mov_recommended',
      'featured_clips' => 'field_mov_featured_clips',
      'videos_gallery' => 'field_mov_videos_gallery',
      'movie_topics' => 'field_mov_movie_topics',
      'movie_genres' => 'field_mov_movie_genres',
      'movie_countries' => 'field_mov_movie_countries',
      'movie_ages' => 'field_mov_movie_ages',
      'movie_category' => 'field_mov_movie_category',
      'movie_tags' => 'field_mov_movie_tags',
      'movie_playlist' => 'field_mov_movie_playlist',
      'videos_preview' => 'field_mov_videos_preview',
      'featured_image_two' => 'field_mov_featured_image_two',
      'title_images' => 'field_mov_title_images',
    ),
    'post_type:page' => 
    array (
      'page_select_header' => 'field_page_page_select_header',
      'page_select_footer' => 'field_page_page_select_footer',
      'turn_off_header' => 'field_page_turn_off_header',
      'turn_on_header_sidebar' => 'field_page_turn_on_header_sidebar',
      'turn_off_footer' => 'field_page_turn_off_footer',
      'title_bar_checkbox' => 'field_page_title_bar_checkbox',
      'tool_bar_checkbox' => 'field_page_tool_bar_checkbox',
      'page_header_absolute' => 'field_page_page_header_absolute',
    ),
    'post_type:person' => 
    array (
      'know' => 'field_person_know',
      'gender' => 'field_person_gender',
      'birthday' => 'field_person_birthday',
      'address' => 'field_person_address',
      'know_as' => 'field_person_know_as',
      'videos_tmdb' => 'field_person_videos_tmdb',
    ),
    'post_format:quote' => 
    array (
      'blog_name_quote' => 'blog_name_quote',
    ),
    'taxonomy:movies_playlist' => 
    array (
      'playlist_image' => 'field_mov_playlist_image',
      'status' => 'field_mov_status',
      'user' => 'field_mov_user',
    ),
    'taxonomy:episodes_playlist' => 
    array (
      'playlist_image' => 'field_ep_playlist_image',
      'status' => 'field_ep_status',
      'user' => 'field_ep_user',
    ),
    'taxonomy:tv_shows_cat' => 
    array (
      'color_background' => 'field_tvs_color_background',
      'color_background2' => 'field_tvs_color_background2',
      'tv_shows_cat_image' => 'field_tvs_tv_shows_cat_image',
    ),
    'taxonomy:tv_shows_playlist' => 
    array (
      'playlist_image' => 'field_tvs_playlist_image',
      'status' => 'field_tvs_status',
      'user' => 'field_tvs_user',
    ),
    'taxonomy:videos_playlist' => 
    array (
      'playlist_image' => 'field_vd_playlist_image',
      'status' => 'field_vd_status',
      'user' => 'field_vd_user',
    ),
    'taxonomy:topics' => 
    array (
      'topic_featured_content' => 'field_topic_featured_content',
      'color_background' => 'field_topic_color_background',
      'color_background2' => 'field_topic_color_background2',
      'topics_image' => 'field_topic_topics_image',
    ),
    'post_type:tv_shows' => 
    array (
      'videos_years' => 'field_tvs_videos_years',
      'videos_tmdb' => 'field_tvs_videos_tmdb',
      'videos_vote' => 'field_tvs_videos_vote',
      'videos_imdb_id' => 'field_tvs_videos_imdb_id',
      'videos_imdb' => 'field_tvs_videos_imdb',
      'videos_badge' => 'field_tvs_videos_badge',
      'featured_clips' => 'field_tvs_featured_clips',
      'videos_trailer_type' => 'field_tvs_videos_trailer_type',
      'videos_trailer_file' => 'field_tvs_videos_trailer_file',
      'videos_trailer_url' => 'field_tvs_videos_trailer_url',
      'tv_shows_seasons' => 'field_tvs_tv_shows_seasons',
      'buy_enable' => 'field_tvs_buy_enable',
      'buy_price' => 'field_tvs_buy_price',
      'rent_enable' => 'field_tvs_rent_enable',
      'rent_price' => 'field_tvs_rent_price',
      'rent_day' => 'field_tvs_rent_day',
      'cast' => 'field_tvs_cast',
      'crew' => 'field_tvs_crew',
      'videos_ads_special' => 'field_tvs_videos_ads_special',
      'tvshow_topics' => 'field_tvs_topics',
      'tvshow_genres' => 'field_tvs_genres',
      'tvshow_countries' => 'field_tvs_countries',
      'tvshow_ages' => 'field_tvs_ages',
      'tvshow_category' => 'field_tvs_category',
      'tvshow_tags' => 'field_tvs_tags',
      'featured_image_two' => 'field_tvs_featured_image_two',
      'title_images' => 'field_tvs_title_images',
    ),
    'user_form:all' => 
    array (
      'jws_date_of_birth' => 'jws_date_of_birth',
      'jws_gender' => 'jws_gender',
      'jws_postcode' => 'jws_postcode',
      'user_phone' => 'user_phone',
    ),
    'post_format:video' => 
    array (
      'blog_video' => 'blog_video',
    ),
    'post_type:videos' => 
    array (
      'videos_type' => 'field_vd_videos_type',
      'videos_file' => 'field_vd_videos_file',
      'videos_url' => 'field_vd_videos_url',
      'video_ratio' => 'field_vd_video_ratio',
      'videos_time' => 'field_vd_videos_time',
      'live_data' => 'field_vd_live_data',
      'videos_ads_special' => 'field_vd_videos_ads_special',
      'videos_preview' => 'field_vd_videos_preview',
    ),
    'post_type:product' => 
    array (
      'shop_single_layout' => 'field_product_shop_single_layout',
      'shop_single_thumbnail_position' => 'field_product_shop_single_thumbnail_position',
      'shop_single_video_type' => 'field_product_shop_single_video_type',
      'product_video' => 'field_product_product_video',
    ),
    'post_type:questions' => 
    array (
      'product_name' => 'field_questions_product_name',
      'product_email' => 'field_questions_product_email',
      'answer_content' => 'field_questions_answer_content',
    ),
  ),
  'generated' => 1789610027,
);
